version: 1
disable_existing_loggers: false
loggers:
  root:
    level: WARNING
    handlers: [rfile]
  douhack:
    level: DEBUG
    handlers: [rfile]
    propagate: false
  # The following SQLAlchemy loggers are used for development only to let you
  # understanding what's actually going on inside SQLAlchemy. You can safely
  # remove them as you wish. 
  sqlalchemy:
    level: WARNING
    handlers: [sa]
    propagate: false
  sqlalchemy.engine:
    level: WARNING
    handlers: [sa]
    propagate: false
  sqlalchemy.dialects:
    level: WARNING
    handlers: [sa]
    propagate: false
  sqlalchemy.pool:
    level: WARNING
    handlers: [sa]
    propagate: false
  sqlalchemy.orm:
    level: WARNING
    handlers: [sa]
    propagate: false
handlers:
  stdout:
    class: logging.StreamHandler
    formatter: debug
    stream: ext://sys.stdout
  stderr:
    class: logging.StreamHandler
    formatter: debug
    stream: ext://sys.stderr
  rfile:
    class: logging.handlers.RotatingFileHandler
    formatter: debug
    filename: /home/wk/src/douhack/logs/douhack.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8
  trfile:
    class: logging.handlers.TimedRotatingFileHandler
    formatter: warning
    filename: /home/wk/src/douhack/logs/douhack.log
    when: midnight
    backupCount: 60
    encoding: utf8
  sa:
    class: logging.handlers.RotatingFileHandler
    formatter: debug
    filename: /home/wk/src/douhack/logs/douhack.log
    maxBytes: 1048576
    backupCount: 5
    encoding: utf8
formatters:
  debug:
    format: '%(asctime)s [%(levelname)s] %(name)s Thread(id=%(thread)d, name="%(threadName)s") %(message)s'
  info:
    format: '%(asctime)s [%(levelname)s] %(name)s %(message)s'
  warning:
    format: '%(asctime)s [%(levelname)s] %(name)s Thread(id=%(thread)d, name="%(threadName)s") %(module)s.%(funcName)s: line %(lineno)d %(message)s'
  error:
    format: '%(asctime)s [%(levelname)s] %(name)s Thread(id=%(thread)d, name="%(threadName)s") %(module)s.%(funcName)s: line %(lineno)d %(message)s'
